#!/bin/bash

# kitty
ln -s ~/.dotfiles/.config/kitty/kitty.conf $HOME/.config/kitty/kitty.conf

# neofetch
ln -s ~/.dotfiles/neofetch/config.conf $HOME/.config/neofetch/config.conf

# tmux
ln -s ~/.dotfiles/.tmux.conf $HOME/.tmux.conf

# zsh p10k
ln -s ~/.dotfiles/zsh/.zshrc $HOME/.zshrc
ln -s ~/.dotfiles/zsh/.p10k.zsh $HOME/.p10k.zsh

# ranger
ln -s ~/.dotfiles/.config/ranger/rc.conf $HOME/.config/ranger/rc.conf

# solargraph
ln -s ~/.dotfiles/.config/solargraph/config.yml $HOME/.config/solargraph/config.yml

# Lazygit
ln -s ~/.dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
